<?php
/**
 * @version 0.0.1
 * @created 2013-03-02 04:19 gmt +1
 * @author dan entous <contact@gmtplusone.com>
 * @copyright © 2013 dan entous
 * @license GNU General Public Licence 3.0 http://www.gnu.org/licenses/gpl.html
 */
namespace Europeana;
use Exception,
		ReflectionClass,
		ReflectionProperty;


/**
 * if the search has results, the hits take place in the "items" array. Each item is an object, and represents a summary of metadata record. The actual content is depending of the profile parameter. The mandatory field are:
 */
class Item {


	/**
	 * @var int
	 */
	public $completeness;


	/**
	 * @var array
	 */
	public $dataProvider;


	/**
	 * @var array
	 */
	public $dcCreator;


	/**
	 * @var array
	 */
	public $edmConceptLabel;


	/**
	 * @var array
	 */
	public $edmPreview;


	/**
	 * @var array
	 */
	public $edmTimespanLabel;


	/**
	 * @var array
	 */
	public $europeanaCollectionName;


	/**
	 * @var int
	 */
	public $europeanaCompleteness;


	/**
	 * @var string
	 * an URL points to the object page in portal, and includes "utm_source=api&utm_medium=api&utm_campaign=BNVFJIIZTH" parameters to track the API-generated visits. This way Europeana and partners can measure the traffic generated by the API, so please keep these parameters as the part of the link.
	 */
	public $guid;


	/**
	 * @var string
	 */
	public $id;


	/**
	 * @var int
	 */
	public $index;


	/**
	 * @var array
	 */
	public $language;


	/**
	 * @var string
	 * an URL points to the object call in API. If you want to retrieve the full metadata object, please follow this link. The link contains the API key, so you should no display directly to the end users.
	 */
	public $link;


	/**
	 * @var array
	 */
	public $provider;


	/**
	 * @var array
	 */
	public $rights;


	/**
	 * @var array
	 */
	public $title;


	/**
	 * @var string
	 */
	public $type;


	/**
	 * @var int
	 */
	public $year;


	/**
	 * @access protected
	 */
	protected $_reflection;


	/**
	 * @access protected
	 */
	protected $_public_properties;


	/**
	 * @var array
	 */
	protected $_response_array;


	/**
	 * @return void
	 */
	protected function populate() {

		if ( empty( $this->_response_array ) ) { return; }

		foreach( $this->_public_properties as $property ) {

			if ( array_key_exists( $property->name, $this->_response_array ) ) {

					$this->{$property->name} = $this->_response_array[ $property->name ];

			}

		}

	}


	public function __construct( $response_array ) {

		$this->_response_array = $response_array;
		$this->_reflection = new ReflectionClass( $this );
		$this->_public_properties = $this->_reflection->getProperties( ReflectionProperty::IS_PUBLIC );
		$this->populate();

	}
	
}